/* Generated By:JavaCC: Do not edit this line. ParserTreeConstants.java Version 6.0_1 */
public interface ParserTreeConstants
{
  public int JJTID = 0;
  public int JJTINTEGER = 1;
  public int JJTVOID = 2;
  public int JJTINTARRAY = 3;
  public int JJTINT = 4;
  public int JJTBOOLEAN = 5;
  public int JJTPROGRAM = 6;
  public int JJTCLASS = 7;
  public int JJTVAR = 8;
  public int JJTMETHOD = 9;
  public int JJTPARAMETERS = 10;
  public int JJTBODY = 11;
  public int JJTRETURN = 12;
  public int JJTINDEX = 13;
  public int JJTASSIGN = 14;
  public int JJTCOND = 15;
  public int JJTTHEN = 16;
  public int JJTELSE = 17;
  public int JJTIF = 18;
  public int JJTDO = 19;
  public int JJTWHILE = 20;
  public int JJTAND = 21;
  public int JJTLOWER = 22;
  public int JJTPLUS = 23;
  public int JJTMINUS = 24;
  public int JJTTIMES = 25;
  public int JJTDIVIDE = 26;
  public int JJTTRUE = 27;
  public int JJTFALSE = 28;
  public int JJTTHIS = 29;
  public int JJTNEWARRAY = 30;
  public int JJTNEWOBJ = 31;
  public int JJTNOT = 32;
  public int JJTLENGTH = 33;
  public int JJTFCALL = 34;


  public String[] jjtNodeName = {
    "ID",
    "INTEGER",
    "void",
    "INTARRAY",
    "INT",
    "BOOLEAN",
    "PROGRAM",
    "CLASS",
    "VAR",
    "METHOD",
    "PARAMETERS",
    "BODY",
    "RETURN",
    "INDEX",
    "ASSIGN",
    "COND",
    "THEN",
    "ELSE",
    "IF",
    "DO",
    "WHILE",
    "AND",
    "LOWER",
    "PLUS",
    "MINUS",
    "TIMES",
    "DIVIDE",
    "TRUE",
    "FALSE",
    "THIS",
    "NEWARRAY",
    "NEWOBJ",
    "NOT",
    "LENGTH",
    "FCALL",
  };
}
/* JavaCC - OriginalChecksum=992c50c25b88dfda9241384bde94ec1a (do not edit this line) */
