/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int AND = 5;
  /** RegularExpression Id. */
  int LOWER = 6;
  /** RegularExpression Id. */
  int PLUS = 7;
  /** RegularExpression Id. */
  int MINUS = 8;
  /** RegularExpression Id. */
  int TIMES = 9;
  /** RegularExpression Id. */
  int DIVIDE = 10;
  /** RegularExpression Id. */
  int LENGTH = 11;
  /** RegularExpression Id. */
  int OPEN_PAREN = 12;
  /** RegularExpression Id. */
  int CLOSE_PAREN = 13;
  /** RegularExpression Id. */
  int COMMA = 14;
  /** RegularExpression Id. */
  int DOT = 15;
  /** RegularExpression Id. */
  int OPEN_BRACK = 16;
  /** RegularExpression Id. */
  int CLOSE_BRACK = 17;
  /** RegularExpression Id. */
  int INT = 18;
  /** RegularExpression Id. */
  int INTARRAY = 19;
  /** RegularExpression Id. */
  int NOT = 20;
  /** RegularExpression Id. */
  int NEW = 21;
  /** RegularExpression Id. */
  int THIS = 22;
  /** RegularExpression Id. */
  int TRUE = 23;
  /** RegularExpression Id. */
  int FALSE = 24;
  /** RegularExpression Id. */
  int ASSIGN = 25;
  /** RegularExpression Id. */
  int BOOLEAN = 26;
  /** RegularExpression Id. */
  int SEMI_COLON = 27;
  /** RegularExpression Id. */
  int WHILE = 28;
  /** RegularExpression Id. */
  int IF = 29;
  /** RegularExpression Id. */
  int ELSE = 30;
  /** RegularExpression Id. */
  int OPEN_BRACES = 31;
  /** RegularExpression Id. */
  int CLOSE_BRACES = 32;
  /** RegularExpression Id. */
  int PUBLIC = 33;
  /** RegularExpression Id. */
  int RETURN = 34;
  /** RegularExpression Id. */
  int EXTENDS = 35;
  /** RegularExpression Id. */
  int CLASS = 36;
  /** RegularExpression Id. */
  int INTEGER_LITERAL = 37;
  /** RegularExpression Id. */
  int IDENTIFIER = 38;
  /** RegularExpression Id. */
  int EMPTY = 39;
  /** RegularExpression Id. */
  int NON_EMPTY = 40;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int MATCH_NON_EMPTY = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\n\"",
    "\"\\t\"",
    "\"\\r\"",
    "\"&&\"",
    "\"<\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"length\"",
    "\"(\"",
    "\")\"",
    "\",\"",
    "\".\"",
    "\"[\"",
    "\"]\"",
    "\"int\"",
    "\"int[]\"",
    "\"!\"",
    "\"new\"",
    "\"this\"",
    "\"true\"",
    "\"false\"",
    "\"=\"",
    "\"boolean\"",
    "\";\"",
    "\"while\"",
    "\"if\"",
    "\"else\"",
    "\"{\"",
    "\"}\"",
    "\"public\"",
    "\"return\"",
    "\"extends\"",
    "\"class\"",
    "<INTEGER_LITERAL>",
    "<IDENTIFIER>",
    "\"\"",
    "<NON_EMPTY>",
  };

}
