/* Generated By:JavaCC: Do not edit this line. ParserTreeConstants.java Version 6.0_1 */
public interface ParserTreeConstants
{
  public int JJTID = 0;
  public int JJTTYPE = 1;
  public int JJTPROGRAM = 2;
  public int JJTCLASS = 3;
  public int JJTVAR = 4;
  public int JJTMETHOD = 5;
  public int JJTPARAMETERS = 6;
  public int JJTVOID = 7;


  public String[] jjtNodeName = {
    "ID",
    "TYPE",
    "PROGRAM",
    "CLASS",
    "VAR",
    "METHOD",
    "PARAMETERS",
    "void",
  };
}
/* JavaCC - OriginalChecksum=409cfaa0c8473f9566f5b9cd996a65a4 (do not edit this line) */
